= Blueprint: Node.js
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

toc::[]

== Overview

This is simple blueprint for a Node.js application with helpful libraries.

== Usage

This repository is defined as GitHub Template. Create an own repo using this as template.

Startup

----
$ npm start
----

== Changelog

|===
| Version | Note

| 0.2
| Add mongodb

| 0.1
| Initial

|===

== Libraries

|===
| Lib | Version | Note

| axios
| 0.21.1
| Successor of the `request` lib

| express
| 4.7.12
| Express, web

| express-prom-bundle
| 6.0.0
| Prometheus, to expose metrics

| prom-client
| 12.0.0
| Prometheus client

| morgan
| 1.10.0
| Logger

| mongodb
| 3.6.3
| MongoDB Client
|===


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.